hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

#noproblem_any_auth:
#    resource: "@NoproblemAnyAuthBundle/Controller/"
#    type:     annotation
#    prefix:   /
    
google_login:
    pattern: /login/check-google

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
