<?php

namespace Noproblem\AuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OAuthUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthUserRepository extends EntityRepository
{
}
